### ISSUE TITLE
Data download script

### ISSUE THREAD

**Issue by shanemcq18** [Willcox-Research-Group/rom-operator-inference-Python3#60]
Data files used in the examples live on the [`data`](https://github.com/Willcox-Research-Group/rom-operator-inference-Python3/tree/data) branch. We should have a script in the `docs/` folder that downloads the data and puts it in the correct place so that the tutorials can be executed locally. This will also enable testing the documentation compilation through GitHub Actions (we had an action previously but it would pass even if a notebook cell failed to execute).

**TODO**:
- [ ] Write the script
- [ ] Update contributor guidelines
- [ ] Remove `.pre-commit.yaml` from the `data` branch?
- [ ] Reinstate GitHub Action for checking that the documentation compiles

**Comment by shanemcq18** [comment]
`.pre-commit.yaml` removed from `data` branch in 463a19c290f494ed325513b785534cbbf81526bc.
